AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Resources:
  ConfigRule:
    Type: 'AWS::Config::ConfigRule'
    Properties:
      ConfigRuleName: guardduty-enabled-centralized
      Scope:
        ComplianceResourceTypes: []
      Description: >-
        A Config rule that checks whether Amazon GuardDuty is enabled in your
        AWS account and region. If you provide an AWS account for
        centralization, the rule evaluates the Amazon GuardDuty results in the
        centralized account. The rule is compliant when Amazo...
      Source:
        Owner: AWS
        SourceIdentifier: GUARDDUTY_ENABLED_CENTRALIZED
      MaximumExecutionFrequency: TwentyFour_Hours
Parameters: {}
Metadata: {}
Conditions: {}
